### PR TITLE
chore: remove unused dependencies

### PR DESCRIPTION
**Pull request by MegaRedHand**
## Description

This PR removes some unused dependencies, as reported by [_cargo-udeps_](https://crates.io/crates/cargo-udeps/0.1.40). Those dependencies are:

- rand_core
- serde_bytes
- rusty-hook (dev)

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
  - [ ] CHANGELOG has been updated.

### CODE REVIEW

**Review by Oppen — APPROVED** [review]
Love it! ❤️

**Comment by Oppen** [comment]
Just for fun, could you check if build times/binary size change?

**Comment by MegaRedHand** [comment]
Compilation time varies by a lot but didn't change much it seems. Size decreased by 8 bytes 🚀 

|      |   BASE  | HEAD     |
|:----:|:-------:|----------|
| time | 11 ±1s  | 11s ±1s  |
| size | 27192 B | 27184 B  |

**Comment by Oppen** [comment]
> Compilation time varies by a lot but didn't change much it seems. Size decreased by 8 bytes 🚀 (in debug)
> 
> BASE	HEAD
> time	11 ±1s	11 ±1s
> size	27192 B	27184 B

Size go brrrrr

**Review by pefontana — APPROVED** [review]
I thougt that the .rusty-hook.toml needed the rusty-hook deps

Tried it and the cargo fmt rusty hook still works so LGTM

**Pull request merged**
