### PR TITLE
feat: make "arbitrary" feature enable `proptest` features

### PR DESCRIPTION
**Pull request by MegaRedHand**
## Description

This PR makes public the `arbitrary` module, with the `proptest::arbitrary::Arbitrary` implementation for `Felt252` along with some helper functions, via the *arbitrary* feature.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
  - [ ] CHANGELOG has been updated.

### CODE REVIEW

**Review by pefontana — APPROVED** [review]

**Comment by Oppen** [comment]
Shouldn't the `arbitrary` feature take care of that already?

**Comment by MegaRedHand** [comment]
The `arbitrary` feature enables the `arbitrary` dependency, while this one enables the `proptest` dependency. Those are two different things. Albeit they both have an `Arbitrary` trait, they are different (it's really confusing).
Do you think that combining the two features would be ok?

**Comment by Oppen** [comment]
Oh. Is this about the `proptest::Arbitrary` and the `quickcheck::Arbitrary`? I would suggest instead those features are either collapsed into one as you suggest or be something like `pt_arbitrary` and `qc_arbitrary` (maybe not abbreviated, however you prefer).

**Comment by MegaRedHand** [comment]
I ended up merging the two flags and added a comment clarifying the difference between [**Arbitrary**](https://docs.rs/arbitrary/latest/arbitrary/trait.Arbitrary.html), and [_Arbitrary_](https://docs.rs/proptest/latest/proptest/arbitrary/trait.Arbitrary.html).

**Review by Oppen — APPROVED** [review]

**Pull request merged**
