### PR TITLE
Add bn254 final exp test for benchmark

### PR DESCRIPTION
**Pull request by feltroidprime**
Subset of Garaga code added to compute bn254 final exp. 
Hints are in fq.cairo, e2.cairo, and e12.cairo (complete list, 8 in total) : 
I tried to put them in the json file also.

https://github.com/lambdaclass/cairo-rs/blob/22648c089c26037a5d8fdff8162da0f0a641db86/cairo_programs/bn254/fq.cairo#L32-L66

https://github.com/lambdaclass/cairo-rs/blob/22648c089c26037a5d8fdff8162da0f0a641db86/cairo_programs/bn254/fq.cairo#L132-L166

https://github.com/lambdaclass/cairo-rs/blob/22648c089c26037a5d8fdff8162da0f0a641db86/cairo_programs/bn254/fq.cairo#L240-L318

https://github.com/lambdaclass/cairo-rs/blob/22648c089c26037a5d8fdff8162da0f0a641db86/cairo_programs/bn254/fq.cairo#L416-L477

https://github.com/lambdaclass/cairo-rs/blob/22648c089c26037a5d8fdff8162da0f0a641db86/cairo_programs/bn254/fq.cairo#L521-L582

https://github.com/lambdaclass/cairo-rs/blob/22648c089c26037a5d8fdff8162da0f0a641db86/cairo_programs/bn254/fq.cairo#L626-L649

https://github.com/lambdaclass/cairo-rs/blob/22648c089c26037a5d8fdff8162da0f0a641db86/cairo_programs/bn254/towers/e2.cairo#L51-L82

https://github.com/lambdaclass/cairo-rs/blob/22648c089c26037a5d8fdff8162da0f0a641db86/cairo_programs/bn254/towers/e12.cairo#L154-L254

### CODE REVIEW

**Comment by Oppen** [comment]
Hi @feltroidprime. Is there any chance you move the test programs into the base `cairo_programs` directory? AFAIR it won't run the memory and trace comparison otherwise, and we want to make sure it matches the reference Python implementation.

I'll do a more in-depth review later, at a high level it looks rather good except for that little detail.

**Comment by feltroidprime** [comment]
I moved the files and updated the imports. 
However I still left the main program in caro_programs/benchmarks. Let me know if this wans't what you expected

**Comment by pefontana** [comment]
> I moved the files and updated the imports. However I still left the main program in caro_programs/benchmarks. Let me know if this wans't what you expected

Thanks a lot @feltroidprime !!
Yes, can you please move the main program to `cairo_programs/`.

Then we will merge it

**Comment by Oppen** [comment]
> I moved the files and updated the imports.
> However I still left the main program in caro_programs/benchmarks. Let me know if this wans't what you expected

If this is meant to run as a benchmark, we have a common pattern where each file has a `run` function and each file its own `main`. Then the benchmark only calls `run` as well, but all tests execute and get their memory compared.

**Comment by pefontana** [comment]
Also, the compilation of the `bn254_final_exp.cairo` is failing

**Pull request closed without merging**
