### PR TITLE
perf: rework `MemoryCell` for cache efficiency

### PR DESCRIPTION
**Pull request by Oppen**
Store data and metadata inline as a single `[u64; 4]` with `32` bytes alignment, fitting a whole number of cells per cache line to reduce evictions and double sharing and to avoid split line access.

Besides performance, an observable change is that now `Memory::get` always returns a `Cow::Owned` variant because the decoding process always creates a new value.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [x] This change requires new documentation.
  - [ ] Documentation has been added/updated.
  - [x] CHANGELOG has been updated.

### CODE REVIEW

**Review by juanbono — APPROVED** [review]

**Review by fmoletta — APPROVED** [review]
Amazing! 🚀

**Review by pefontana — CHANGES_REQUESTED** [review]
Before merging I think it will be nice to add a workflow that benchmarks the hyper-threading performance, so we can measure the improvement done here

**Review by pefontana — APPROVED** [review]

**Review by pefontana — CHANGES_REQUESTED** [review]
We need to check the benchmarks here, they are giving wrong numbers

**Review by pefontana — APPROVED** [review]

**Comment by pefontana** [comment]
Benchmarks are going OK now

**Pull request merged**
