### PR TITLE
fix to_signed_felt doc

### PR DESCRIPTION
**Pull request by greged93**
# Fix doc tests

## Description

The current documentation for `to_signed_felt` and `take_until_unbalanced` are incorrect and caused the doc tests to fail.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
- [x] Documentation has been added/updated.
- [ ] CHANGELOG has been updated.

### CODE REVIEW

**Review by fmoletta — APPROVED** [review]

**Review by MegaRedHand — APPROVED** [review]

**Comment by Oppen** [comment]
@MegaRedHand `to_signed_felt` will be removed after merging the standard felt, right? If that's so, @greged93 would you agree to closing this PR?

**Comment by MegaRedHand** [comment]
The function won't be removed in the foreseeable future. We can merge this for now.

Context: we are changing the underlying implementation of `Felt252` for performance reasons, and some of its API might change. We still need to be able to treat felts as signed for some hints, so we still need this method.

**Comment by greged93** [comment]
Will rebase and update the change log then :)

**Comment by greged93** [comment]
I think the PR can be closed, doctests were fixed by #1281 :)

**Pull request closed without merging**
